# Generated by Django 4.1.13 on 2024-01-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('postdate', models.DateField()),
                ('extractdate', models.DateField()),
                ('summary', models.TextField()),
                ('salary', models.CharField(max_length=50)),
                ('job_url', models.URLField()),
            ],
        ),
    ]
