# Generated by Django 4.1.13 on 2024-01-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0002_alter_job_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
